name: code_test_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.3
  intl: ^0.17.0  
  sqflite: ^2.0.1
  redux: ^5.0.0
  flutter_redux: ^0.8.2
  sembast: ^3.1.0+2 
  url_launcher: ^6.0.0
  fluttertoast: ^8.0.7
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fl_chart: ^0.40.6
  flutter_bloc: ^7.0.1
  flutter_svg: ^0.22.0
  shimmer: ^2.0.0
dev_dependencies:
  change_app_package_name: ^1.0.0
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_app.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
